DROP TABLE IF EXISTS CUSTOMER;
CREATE TABLE CUSTOMER
(
    ID    SERIAL PRIMARY KEY,
    NAME  VARCHAR(255) NOT NULL,
    EMAIL VARCHAR(255) NOT NULL,
    DATA  VARCHAR      NOT NULL
);

DROP TABLE IF EXISTS MOVIE;
CREATE TABLE MOVIE
(
    ID          SERIAL PRIMARY KEY,
    TITLE       VARCHAR(255) NOT NULL,
    GENRE       VARCHAR      NOT NULL,
    DESCRIPTION VARCHAR      NOT NULL,
    POSTER_ID   VARCHAR(100) NOT NULL,
    STATE       VARCHAR(100) NOT NULL
);

DROP TABLE IF EXISTS BOOKING;
CREATE TABLE BOOKING
(
    ID          SERIAL PRIMARY KEY,
    CUSTOMER_ID INTEGER                  NOT NULL,
    MOVIE_ID    INTEGER                  NOT NULL,
    START_TIME  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    SEATS       INTEGER                  NOT NULL,
    BOOKED_AT   TIMESTAMP WITH TIME ZONE NOT NULL
);