name: Build and Publish Image

on:
  push:
    branches: [ "main" ]

permissions:
  id-token: write
  contents: read
  checks: write
  packages: write

jobs:
  build:
    name: Build and Publish
    runs-on: ubuntu-latest

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Cache local Maven repository
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build and Test with Maven
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true test
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Report Maven Test Results
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Maven Test Results
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true

      - name: Build and Publish Image
        run: mvn --batch-mode -DskipTests package
        env:
          GITHUB_TOKEN: ${{ github.token }}

  deploy-gcp:
    name: Deploy to GCP
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: "Authenticate to GCP"
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: 'projects/336669607852/locations/global/workloadIdentityPools/github-wif-pool/providers/github-wif-provider'
          service_account: 'github-sa@cinema-tickets-hexa-workshop.iam.gserviceaccount.com'

      - name: "Push image to GCP"
        run: |
          docker buildx imagetools create \
            --tag 'europe-west1-docker.pkg.dev/cinema-tickets-hexa-workshop/docker-images/service:latest' \
            'ghcr.io/cfranzen/cinema-tickets-hexa-workshop/service'